CREATE TABLE IF NOT EXISTS `#__EMPRESA`(
  `COD_EMPRESA` INT NOT NULL AUTO_INCREMENT,
  `COD_RUBRO` INT,
  `COD_TIPO` INT,
  `NOMBRE_EMPRESA` VARCHAR(25),
  `TIPO_EMPRESA` VARCHAR(3),
  `TAMANO` VARCHAR(7)
  PRIMARY KEY (`COD_EMPRESA`)
  );
  
CREATE TABLE IF NOT EXISTS `#__RUBRO`(
  `COD_EMPRESA` INT NOT NULL AUTO_INCREMENT,
  `COD_RUBRO` INT,
  `COD_TIPO` INT,
  `NOMBRE_RUBRO` VARCHAR(30),
  `DESC_RUBRO` VARCHAR(50),
  PRIMARY KEY (`COD_RUBRO`)
  );

CREATE TABLE IF NOT EXISTS `#__PUESTO`(
  `COD_PUESTO` INT NOT NULL AUTO_INCREMENT,
  `COD_TIPO` INT,
  `COD_RUBRO` INT,
  `NOMBRE_PUESTO` VARCHAR(30),
  `CANTIDAD_PUESTO` INT,
  PRIMARY KEY (`COD_PUESTO`)
  );

CREATE TABLE IF NOT EXISTS `#__TIPOUSARIO`(
  `COD_TIPO` INT NOT NULL AUTO_INCREMENT,
  `TIPO` INT,
  `COD_TIPO` INT,
  `DESCRIPCION` VARCHAR(30),
  PRIMARY KEY (`COD_TIPO`)
  );

CREATE TABLE IF NOT EXISTS `#__USUARIO`(
  `COD_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `COD_TIPO` INT,
  `NOMBRE_USUARIO` VARCHAR(30),
  `PASS_USUARIO` VARCHAR(50),
  PRIMARY KEY (`COD_USUARIO`)
  );


